---
# tasks file for ssh_key_deployment
#
# This task deploys ssh keys on linux systems.
#

- name: get and merge all ssh keys
  ansible.builtin.debug:
    msg: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ ssh_key_deployment_key }}"
  register: ssh_key_deployment_key_list

- name: deploy ssh keys
  ansible.posix.authorized_key:
    exclusive: "{{ ssh_key_deployment_exclusive }}"
    key: "{{ ssh_key_deployment_key_list.results | map(attribute='msg') | join('\n') }}"
    state: "{{ ssh_key_deployment_state }}"
    user: "{{ ssh_key_deployment_user }}"
